application:
  max-allowed-books: 2
spring:
  datasource:
    url: jdbc:postgresql://172.16.1.121:5432/library
    username: library
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
